stages:
  - build
  - dev

build-dev:
  stage: dev
  only:
    - main
    - development
    #- merge_requests
  tags:
    - frontend
  script:
    - cd /var/www/ovir/frontend/
    - pwd
    - whoami
    - git stash
    - git pull origin main
    - npm install --force
    - npm run build
    - find ./dist -type d -exec chmod 755 {} \;
    - find ./dist -type f -exec chmod 644 {} \;
cache:
  paths:
    - node_modules/

build-prod:
  stage: build
  only:
    - main

  tags:
    - frontend
  script:
    - cd /home/front
    - pwd
    - whoami
    - git pull origin production || fail
    - yarn install
    - yarn build
  cache:
    paths:
      - node_modules/
